#  ___________________________________________________
# |  _____                       _____ _ _       _    |
# | |  __ \                     |  __ (_) |     | |   |
# | | |__) |__ _ __   __ _ _   _| |__) || | ___ | |_  |
# | |  ___/ _ \ '_ \ / _` | | | |  ___/ | |/ _ \| __| |
# | | |  |  __/ | | | (_| | |_| | |   | | | (_) | |_  |
# | |_|   \___|_| |_|\__, |\__,_|_|   |_|_|\___/ \__| |
# |                   __/ |                           |
# |  GNU/Linux based |___/  Multi-Rotor UAV Autopilot |
# |___________________________________________________|
#
# System Parameters Configuration File
#
# Copyright (C) 2014 Tobias Simon, Ilmenau University of Technology
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


aircomm:
   id: 0
   psk: "This is the PenguPilot Standard Pre-Shared Key for NRF24L01+ Communication"


sensors:
   gps:
      serial_path: "/dev/ttyO2"
      serial_speed: 115200
   remote:
      serial_path: "/dev/ttyO0"

powerman:
   beeper_enabled: False
   priority: 94
   gpio_i2c_bus: 3
   gpio_i2c_address: 0x11
   gpio_power_pin: 0
   battery_cells: 4
   battery_low_cell_voltage: 3.5
   low_voltage_hysteresis: 10.0 # battery needs to go below battery_low_cell_voltage for this time period in order to trigger a low power event
   battery_capacity: 6.6
   power_save_timeout: 60.0
   voltage_adc: 7
   current_adc: 2
   adc_2_voltage: 'lambda x: (x + 27.0951) / 117.1319'
   adc_2_current: 'lambda x: 0.0303 * (2500 - x) + 0.4'

icarus:
   takeoff:
      standard_rel_z: 4.0

   landing:
      motors_off_z: 0.4
      z_low: 0.5


pilot:
   logger:
      level: 3
      details: 2

   ahrs:
      beta: 0.05
      yaw_bias: -0.1999999999999993
      pitch_bias: 0.019999999999999962
      roll_bias: -0.02

   cal:
      acc_bias_x:  0.0
      acc_bias_y:  0.0
      acc_bias_z:  0.0
      acc_scale_x: 1.0
      acc_scale_y: 1.0
      acc_scale_z: 1.0
      mag_bias_x:  0.0
      mag_bias_y:  0.0
      mag_bias_z:  0.0
      mag_scale_x: 1.0
      mag_scale_y: 1.0
      mag_scale_z: 1.0

   manual_control:
      pitch_roll_speed_max: 45.0 # [deg/s]
      pitch_roll_angle_max: 45.0 # [deg]
      yaw_speed_max: 45.0 # maximum yaw rotation speed [deg/s]
      vert_speed_max: 0.3
      horiz_speed_max: 1.3 # maximal horizontal speed
      gps_deadzone: 0.1 # if magnitude of gps speed sticks are lower than this value, gps position is locked
      gas_deadzone: 0.1 # if magnitude of centered gas stick is lower than this value, altitude is locked

   controllers:

      stabilizing:
         att_kp: 4.19227650348e-01
         att_ki: 3.13780298778e+00
         att_kii: 3.45789342669e+00
         att_kd: 2.94830266817e-02
         yaw_kp: 0.0417780282447742
         yaw_ki: 0.3259955464790617
         yaw_kii: 0.3710534021821698
         yaw_kd: 0.002657035449808173                                                                                                                                   
         filt_fg: 10.0
         filt_d: 0.95
         jxx_jyy: 0.0097
         jzz: 0.0057292965
         tmc: 0.06

      ne_speed:
         p: 2.0
         i: 0.0
         i_max: 0.0
      
      attitude:
         p: 1.0
         i: 0.01
         i_max: 0.2
         d: 0.1

      u_speed:
         p: 5.0
         i: 0.05
         imax: 0.25

      u_pos:
         p: 2.0 
         i: 0.01                                                                                                                                                       
         imax: 0.2
         d: 0.2                                                                                                                                                        

      yaw:
         p: 0.24
         i: 0.7
         i_max: 0.5
         d: 0.0
         pid_lim: 0.2

      navigation:
         speed_min: 0.5
         speed_std: 2.0
         speed_max: 3.5
         sqrt_shift: 3.0
         sqrt_scale: 0.25
         square_shift: 0.5
         pos_i: 0.015
         pos_i_max: 5.0
         ortho_p: 0.0

   kalman_pos:
      ultra_noise: 0.05
      baro_noise: 0.05
      gps_noise: 0.03
      process_noise: 1.0e-6

   sensors:
      rc_dsl:
         serial_port: "/dev/ttyO0"

