#  ___________________________________________________
# |  _____                       _____ _ _       _    |
# | |  __ \                     |  __ (_) |     | |   |
# | | |__) |__ _ __   __ _ _   _| |__) || | ___ | |_  |
# | |  ___/ _ \ '_ \ / _` | | | |  ___/ | |/ _ \| __| |
# | | |  |  __/ | | | (_| | |_| | |   | | | (_) | |_  |
# | |_|   \___|_| |_|\__, |\__,_|_|   |_|_|\___/ \__| |
# |                   __/ |                           |
# |  GNU/Linux based |___/  Multi-Rotor UAV Autopilot |
# |___________________________________________________|
#
# Services Configuration File
#
# Copyright (C) 2014 Tobias Simon, Integrated Communication Systems Group, TU Ilmenau
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


# high-priority system services:

autopilot:
   binary: 'autopilot/service/autopilot'
   depends: [gpsp, geomag, powerman, arduino, rc_cal]
   priority: sys_high


# medium-priority system services:

icarus:
   binary: 'icarus/service/icarus.py'
   depends: [autopilot]
   priority: sys_medium

arduino:
   binary: 'arduino/service/arduino'
   platforms: [exynos_quad]
   priority: sys_medium

rc_cal:
   binary: 'rc_cal/service/rc_cal'
   depends: [remote, arduino]
   priority: sys_medium

ads1x15:
   binary: 'ads1x15/service/ads1x15.py'
   platforms: [pi_quad]
   priority: sys_medium

gpsp:
   binary: 'gpsp/service/gpsp'
   priority: sys_medium

twl4030_madc:
   binary: 'twl4030_madc/service/twl4030_madc.py'
   platforms: [overo_quad]
   priority: sys_medium

remote:
   binary: 'remote/service/remote'
   platforms: [overo_quad, pi_quad]
   priority: sys_medium


# low-priority system services:

opcd:
  binary: 'opcd/service/opcd.py'
  priority: sys_low

mavlink:
  binary: 'mavlink/service/mavlink.py'
  priority: sys_low

powerman:
  binary: 'powerman/service/powerman.py'
  depends: [arduino, twl4030_madc, ads1x15]
  priority: sys_low

display:
  binary: 'display/service/display.py'
  platforms: [overo_quad]
  depends: [powerman, geomag, elevmap, rc_cal]
  priority: sys_low

emerg_kill:
  binary: 'emerg_kill/service/emerg_kill.py'
  priority: sys_low

blackbox:
  binary: 'blackbox/service/blackbox.py'
  priority: sys_low

aircomm:
  binary: 'aircomm/service/aircomm.py'
  priority: sys_low

heartbeat:
  binary: 'heartbeat/service/heartbeat.py'
  depends: [gpsp, powerman, aircomm]
  priority: sys_low

geomag:
  binary: 'geomag/service/geomag.py'
  depends: [gpsp]
  priority: sys_low

elevmap:
  binary: 'elevmap/service/elevmap.py'
  depends: [gpsp]
  priority: sys_low

teensy_taranis:
  binary: 'teensy_taranis/service/teensy_taranis.py'
  priority: sys_low

# application-level services:

gpstime:
  binary: 'gpstime/service/gpstime'
  depends: [gpsp]
  priority: app

wifi_sensor:
  binary: 'wifi_sensor/service/wifi_sensor.py'
  priority: app

wifi_loc:
  binary: 'wifi_loc/service/wifi_loc.py'
  depends: [gpsp, wifi_sensor]
  priority: app

log_proxy:
  binary: 'logger/service/log_proxy.py'
  priority: app

file_logger:
  binary: 'logger/service/file_logger.py'
  depends: [log_proxy]
  priority: app

gps_logger:
  binary: 'logger/service/gps_logger.py'
  depends: [gpstime]
  priority: app

