#  ___________________________________________________
# |  _____                       _____ _ _       _    |
# | |  __ \                     |  __ (_) |     | |   |
# | | |__) |__ _ __   __ _ _   _| |__) || | ___ | |_  |
# | |  ___/ _ \ '_ \ / _` | | | |  ___/ | |/ _ \| __| |
# | | |  |  __/ | | | (_| | |_| | |   | | | (_) | |_  |
# | |_|   \___|_| |_|\__, |\__,_|_|   |_|_|\___/ \__| |
# |                   __/ |                           |
# |  GNU/Linux based |___/  Multi-Rotor UAV Autopilot |
# |___________________________________________________|
#
# SCL Configuration File
#
# Copyright (C) 2014 Tobias Simon, Ilmenau University of Technology
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


- name: gvfa
  sockets:
  - gvfa: sub

- name: elevmap
  sockets:
   - gps: sub
   - elev: pub

- name: geomag
  sockets:
   - gps: sub
   - decl: pub

- name: gpsp
  sockets:
   - opcd_ctrl: req
   - gps: pub
   - sats: pub

- name: svctrl
  sockets:
   - opcd_ctrl: req

- name: gps_test
  sockets:
   - gps: sub

- name: gpx_logger
  sockets:
   - gps: sub

- name: twl4030_madc
  sockets:
   - power: pub
   - opcd_ctrl: req

- name: console_logger
  sockets:
   - ap_log: sub

- name: remote
  sockets:
   - remote: pub
   - opcd_ctrl: req

- name: arduino
  sockets:
   - power: pub
   - remote: pub
   - opcd_ctrl: req

- name: ads1x15
  sockets:
   - power: pub
   - opcd_ctrl: req

- name: mission
  sockets:
   - icarus_ctrl: req
   - icarus_state: sub

- name: icarus
  sockets:
   - icarus_ctrl: rep
   - icarus_state: pub
   - ap_ctrl: req
   - ap_mon: sub
   - powerman: sub

- name: wifi_sensor
  sockets:
   - networks: pub

- name: blackbox
  sockets:
   - blackbox: sub

- name: autopilot
  sockets:
   - ap_log: pub
   - blackbox: pub
   - gps: sub
   - decl: sub
   - remote: sub
   - ap_ctrl: rep
   - ap_mon: pub
   - power: sub
   - motors_spinning: pub
   - gvfa: pub
   - opcd_ctrl: req
   - opcd_event: sub

- name: optimizer
  sockets:
   - opcd_ctrl: req
   - blackbox: sub

- name: pilot_shell
  sockets:
   - ap_ctrl: req
   - ap_mon: sub

- name: powerman
  sockets:
   - powerman_ctrl: rep
   - power: sub
   - powerman: pub
   - opcd_ctrl: req

- name: opcd
  sockets:
   - opcd_ctrl: rep
   - opcd_event: pub

- name: opcd_shell
  sockets:
   - opcd_ctrl: req

- name: aircomm
  sockets:
   - aircomm_in: sub
   - aircomm_out: pub
   - opcd_ctrl: req

- name: display
  sockets:
   - motors_spinning: sub
   - gps: sub
   - powerman: sub
   - remote: sub
   - sats: sub
   - decl: sub

- name: heartbeat
  sockets:
   - gps: sub
   - powerman: sub

- name: aircomm_app
  sockets:
   - aircomm_out: sub
   - aircomm_in: pub

- name: wifi_loc
  sockets:
   - networks: sub
   - gps: sub

