#  ___________________________________________________
# |  _____                       _____ _ _       _    |
# | |  __ \                     |  __ (_) |     | |   |
# | | |__) |__ _ __   __ _ _   _| |__) || | ___ | |_  |
# | |  ___/ _ \ '_ \ / _` | | | |  ___/ | |/ _ \| __| |
# | | |  |  __/ | | | (_| | |_| | |   | | | (_) | |_  |
# | |_|   \___|_| |_|\__, |\__,_|_|   |_|_|\___/ \__| |
# |                   __/ |                           |
# |  GNU/Linux based |___/  Multi-Rotor UAV Autopilot |
# |___________________________________________________|
#
# SCL Configuration File
#
# Copyright (C) 2014 Tobias Simon, Integrated Communication Systems Group, TU Ilmenau
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

- name: ofs
  sockets:
   - oflow: pub

- name: gps_logger
  sockets:
   - gps: sub
   - time_set: sub

- name: log_proxy
  sockets:
   - log_data: pull
   - log_data_pub: pub

- name: file_logger
  sockets:
   - log_data_pub: sub

- name: mavlink
  sockets:
   - gps: sub
   - power: sub
   - gps: pub
   - sats: pub

- name: gpstime
  sockets:
   - gps: sub
   - time_set: pub

- name: elevmap
  sockets:
   - gps: sub
   - elev: pub

- name: geomag
  sockets:
   - gps: sub
   - decl: pub

- name: gpsp
  sockets:
   - gps: pub
   - sats: pub

- name: svctrl

- name: gps_test
  sockets:
   - gps: sub

- name: twl4030_madc
  sockets:
   - power: pub

- name: console_logger
  sockets:
  - log_data_pub: sub

- name: remote
  sockets:
   - rc_raw: pub

- name: arduino
  sockets:
   - power: pub
   - rc_raw: pub

- name: ads1x15
  sockets:
   - power: pub

- name: mission
  sockets:
   - icarus_ctrl: req
   - icarus_state: sub

- name: icarus
  sockets:
   - icarus_ctrl: rep
   - icarus_state: pub
   - ap_ctrl: req
   - ap_mon: sub
   - powerman: sub

- name: wifi_sensor
  sockets:
   - networks: pub

- name: blackbox
  sockets:
   - blackbox: sub

- name: autopilot
  sockets:
   - blackbox: pub
   - gps: sub
   - decl: sub
   - rc_cal: sub
   - ap_ctrl: rep
   - ap_mon: pub
   - power: sub
   - motors_spinning: pub
   - elev: sub
   - obj_pos: sub

- name: opcd_shell
  sockets:
   - opcd_ctrl: req

- name: optimizer
  sockets:
   - blackbox: sub

- name: pilot_shell
  sockets:
   - ap_ctrl: req
   - ap_mon: sub

- name: powerman
  sockets:
   - powerman_ctrl: rep
   - power: sub
   - powerman: pub

- name: opcd
  sockets:
   - opcd_event: pub
   - opcd_ctrl: rep

- name: object_tracking
  sockets:
    - obj_pos: pub
    - ap_mon: sub

- name: aircomm
  sockets:
   - aircomm_in: sub
   - aircomm_out: pub

- name: rc_cal
  sockets:
   - rc_raw: sub
   - rc_cal: pub

- name: rc_cal_tool
  sockets:
   - rc_raw: sub

- name: rc_cal_dump
  sockets:
   - rc_cal: sub

- name: display
  sockets:
   - motors_spinning: sub
   - gps: sub
   - powerman: sub
   - rc_cal: sub
   - sats: sub
   - decl: sub
   - elev: sub

- name: teensy_taranis
  sockets:
   - gps: sub
   - power: sub

- name: heartbeat
  sockets:
   - gps: sub
   - powerman: sub

- name: aircomm_app
  sockets:
   - aircomm_out: sub
   - aircomm_in: pub

- name: wifi_loc
  sockets:
   - networks: sub
   - gps: sub

